env:
  es6: true
  browser: true
  commonjs: true
  jest: true

extends: ['eslint-config-airbnb']

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 9
  sourceType: module

plugins: ['react']

settings:
  react:
    version: '17'

rules:
  jsx-a11y/label-has-associated-control: off
